name: CI

permissions:
  id-token: write

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches: [main]
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Static analysis
        run: dart analyze

      - name: Run tests
        run: dart test --coverage=coverage

      - name: Collect coverage
        run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: coverage/lcov.info
